/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next"
import { AppHead } from "../components/app-head";
import MobileHeader from "../components/mobile-header";
import styles from '../styles/Legal.module.scss';
import Image from "next/image";
import LegalHeader from "../components/legal-header";
import Footer from "../components/Footer";
import LegalContainer from "../components/legal-container";



const Terms: NextPage = () => {

    return (
        <>
            <LegalContainer>

                <h2 >Privacy Policy</h2>
                <p>StoryPlace, Inc. (&ldquo;StoryPlace,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) respects the sensitive nature of any personal information you provide to us.&nbsp; We have created this Privacy Policy in order to demonstrate our commitment to the privacy of those who use our mobile applications, <a href="http://www.storyplace.com/" target="_blank" rel="noopener noreferrer">www.Storyplace.com</a>, as well as a number of related services (our &ldquo;Services&rdquo;). This Privacy Policy describes our information collection, storage and disclosure practices and the choices you have regarding how your personal information is collected and used by us and our e-commerce providers.&nbsp; By accessing and using our Services, you consent to the collection, use and disclosure of information through our Services as described in this Privacy Policy.&nbsp;</p>
                <p>Residents of the European Economic Area (&ldquo;EEA&rdquo;), which includes the member states of the European Union (&ldquo;EU&rdquo;), should consult the sections of this policy relating to the &ldquo;Rights of EEA Residents&rdquo; and &ldquo;International Data Transfers&rdquo; for provisions that may apply to them.</p>
                <p>California residents should consult the section titled &ldquo;Your California Privacy Rights&rdquo; for rights that apply to them.</p>
                <p>We reserve the right to change this Privacy Policy at any time.&nbsp; In the event we make changes to this Privacy Policy, such policy will be re-posted in the &ldquo;Privacy&rdquo; section of our websites or applications with the date such modifications were made indicated on the top of the page or we may contact you to inform you about the revisions with a link to the revised Privacy Policy.&nbsp; All changes are effective on the date listed at the top of this page and will apply to all information that we have about you.&nbsp; Your continued use of our Services after any change is posted indicates your acceptance of the changes and your continued consent to our processing of your Personal Information.&nbsp; If at any point you do not agree to any portion of the Privacy Policy then in effect you should immediately stop using our Services.&nbsp; Because this Privacy Policy contains legal obligations we encourage you to review this Privacy Policy carefully.&nbsp; If you have any questions concerning this Privacy Policy or our information collection, storage and disclosure practices, please contact us at support@storyplace.com or mail us at StoryPlace, Inc., StoryPlace HQ, 450 N Palm Dr., Beverly Hills, CA 90210.</p>
                <p><strong>Personal Information That We Collect and How We Use It</strong></p>
                <p>StoryPlace collects Personal Information about you when you use our Services.&nbsp; &ldquo;Personal Information&rdquo; is information that may be used to directly or indirectly identify you, including your name, Pen Name, e-mail address, physical address, phone number or other information about you.&nbsp; The majority of such Personal Information is collected when you register to use our applications, website or StoryPlace Studio, use our Services, including subscribing, request information or updates or otherwise provide us with your contact information.&nbsp; You may also add details to your profile, such as a profile photo, biographical information and other Personal Information.&nbsp; Some of this Personal Information will be required if you wish to partake in the Services that we provide, including using the application.</p>
                <p>In general, the type of Personal Information we collect includes, but is not limited to:</p>
                <ul>
                    <li>Personal Information to contact you regarding our Services or matters of interest;</li>
                    <li>Personal Information necessary to use the Services that you have requested, including establishing an account and subscribing to the Services;</li>
                    <li>Un-identifiable and aggregated Personal Information pertaining to your visits to our websites or applications that help us maintain the appropriate features, functionality and user experience</li>
                </ul>
                <p>We and our e-commerce provider use that data to: (i) enable you to log in to use the Services; (ii) allow you to subscribe to our Services; (iii) guard against potential fraud; (iv) contact you if there is a problem with your account; (v) provide answers to your inquiries or questions; and (vi) maintain regular communication with you as may be necessary to inform you of offers, updates and other information regarding StoryPlace and our Services.</p>
                <h3>Social Networks</h3>
                <p>If you choose to connect to us through a third-party social network such as Facebook, Twitter, Instagram and other networks (each, a &ldquo;Social Network&rdquo;), we may collect Personal Information from your profile on such Social Network, such as your name, user name, and e-mail address.&nbsp; In addition, our mobile applications offer features that will allow you to share information from our mobile applications to a Social Network or share information from our Social Network sites. &nbsp; If you decide to use such features, they may allow the sharing and collection of information both to and from such Social Network so you should check the privacy policy of each Social Network before using such features.</p>
                <h3>Non-Identifiable Data and Aggregated Personal Information</h3>
                <p>Regardless of whether you register for an account or submit information to us, StoryPlace and third parties performing e-commerce services for us may send one or more "cookies" to your computer.&nbsp; Cookies are small text files placed on your web browser when you visit our Site that store information on your computer, such as your site preferences.&nbsp; We use cookies when you sign in to keep track of your personal session.&nbsp; We also use cookies to track your activity on the site as a unique person.&nbsp; For security purposes, all of this information is stored in encrypted form.&nbsp; This data may be used to display information about our Services on websites operated by third parties.</p>
                <p>You can set your web browser to inform you when cookies are set, or to prevent cookies from being set altogether.&nbsp; Please note, however, that if you decline to use cookies, you may experience reduced functionality and slower site response times.</p>
                <p>StoryPlace or our service providers, including FireBase, Google Analytics and Apple Develop App Analytics, may also collect web surfing data related to your use of our website.&nbsp; Such information may include: your Internet Protocol (IP) address, browser type, and internet service provider (ISP); your operating system; which of our web pages you access and how frequently you access them; referral or exit pages; click stream data; and the dates and times that you visit the websites.&nbsp; This data may be collected using cookies, web beacons, page tags or similar tools.&nbsp; As with cookies, the web surfing information is anonymous, "click stream" transactional data that is not associated with any users as individuals.</p>
                <p>Web surfing data and similar information may be aggregated or anonymized for administrative purposes.&nbsp; StoryPlace may, for example, use this aggregated information in the administration of our website to improve its usability and to evaluate the success of particular marketing and advertising campaigns, search engine optimization strategies, and other marketing activities.&nbsp; We also use it to help optimize the website based on the needs of our users.</p>
                <h3>How and When Your Information Is Shared With Other Parties</h3>
                <p>StoryPlace does not sell, trade or license Personal Information about its users for marketing purposes.&nbsp; We do, however, work with a number of trusted partners who perform vital functions as part of our operations, including processing payments for subscriptions.&nbsp; We do not share your Personal Information unless it is necessary to fulfill our responsibilities, including providing information or Services.&nbsp;</p>
                <p>As part of our mission to remind people that everyone has a story to tell and every story has a lesson to teach, we may share your Pen Name, or stories and the location information associated with your stories outside of our mobile applications.&nbsp; For example, we may share this information on our public websites or in our promotional materials in order to encourage other users to share their Stories and to promote a culture of Stories worldwide.&nbsp; Note that StoryPlace&rsquo;s rights to and in the Stories you share on StoryPlace are set out in the <a href="https://storyplacestudio.com/terms/" target="_blank" rel="noopener noreferrer">Terms of Use</a>.</p>
                <h3>Additional Sharing of Information</h3>
                <p>We may engage third parties to help us carry out certain other internal functions such as subscription processing, client services, or other data collection relevant to our business.&nbsp; Personal Information is shared with these third parties only to the extent necessary for us to process the transactions you initiate or perform other specific services.&nbsp; Our partners are legally required to keep your Personal Information private and secure.</p>
                <p>We may share your Personal Information with law enforcement or other government agencies as required by law or for the purposes of limiting fraud. We reserve the right to disclose your Personal Information when we believe that disclosure is necessary to protect our rights or to comply with a judicial proceeding, court order or legal process. We further reserve the right to disclose any of your Personal Information that we believe, in good faith, appropriate or necessary to take precautions against liability, to investigate and defend against any third-party claims or allegations, to assist government enforcement agencies, to protect the security or integrity of the Site or our services, or to protect the rights, property or personal safety of StoryPlace, its users, issuers, or others.</p>
                <p>We will not share your Personal Information if such sharing is prohibited by applicable privacy and data protection law, including, without limitation, the EEA&rsquo;s General Data Protection Regulation effective May 25, 2018.</p>
                <h3>EEA Residents</h3>
                <p>This section of the Privacy Policy is applicable to residents of the European Economic Area (&ldquo;EEA&rdquo;).&nbsp; The EEA consists of the member states of the European Union, i.e., Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden and the United Kingdom, and Iceland, Liechtenstein, and Norway.&nbsp; This section also applies to residents of Switzerland and, in the event of its departure from the EU, residents of the United Kingdom. &nbsp; Residents of the EEA and Switzerland are referred to here as &ldquo;EEA Residents.&rdquo;</p>
                <p>From May 25, 2018, all processing of Personal Information of EEA Residents is performed by StoryPlace in accordance with the General Data Protection Regulation (2016/679) of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons regarding the processing of Personal Information and on the free movement of such data (&ldquo;GDPR&rdquo;).</p>
                <p>Under the GDPR, StoryPlace is both the controller and a co-processor of the Personal Information of EEA Residents.&nbsp; StoryPlace&rsquo;s purpose for collecting and processing Personal Information from EEA Residents is to authenticate subscription to our mailing lists and our Services. The legal basis for collecting Personal Information for subscribing to our e-mail lists and Services is your consent, including during the subscription process.&nbsp; You may withdraw consent for obtaining such communications by following the &ldquo;Unsubscribe&rdquo; instructions on any communication or by contacting us at support@storyplace.com.</p>
                <p>We use Stripe to process subscriptions, including for EEA Residents.</p>
                <p>EEA Residents may obtain information about the Personal Information that StoryPlace holds about them by contacting StoryPlace at support@storyplace.com.</p>
                <h3>International Data Transfers</h3>
                <p>If you are resident outside the United States, including in the EEA, we transfer Personal Information provided by you for processing in the United States.&nbsp; Under the GDPR, StoryPlace is considered a &ldquo;controller&rdquo; and a &ldquo;co-processor&rdquo; of the Personal Information of EEA Residents.&nbsp; By providing Personal Information to StoryPlace for the purpose of obtaining Services, you consent to the processing of such data in the United States.&nbsp; The transfer of your Personal Information to the United States is necessary for the performance of a contract between you and StoryPlace for obtaining Services.&nbsp;</p>
                <p>Please note that the United States does not have data protection laws equivalent to those in the EEA and other jurisdictions.</p>
                <p>Notifications and Communications from Our Site</p>
                <h3>Communications Regarding Our Services</h3>
                <p>We will send you email notifications and free newsletters from time to time with offers, suggestions and other information.&nbsp; Some notifications are communications relating to us and our Services.&nbsp; You may &ldquo;opt-out&rdquo; from receiving such communications by following the &ldquo;Unsubscribe&rdquo; instructions provided in the e-mail.&nbsp;</p>
                <h3>Legal or Security Communications</h3>
                <p>We also send out notices that are required for legal or security purposes.&nbsp; For example, certain notifications are sent for your own protection.&nbsp; In other cases, these notifications involve changes to various legal agreements, such as the Privacy Policy or Terms of Use.&nbsp; Generally, you may not opt out of such emails.</p>
                <h3>Account and Order Communications</h3>
                <p>If you subscribe to our Services, we may send you communications regarding such Services.&nbsp; We may also send communications providing customer support or responses to questions regarding the operation of the Services.&nbsp; Generally, you may not opt out of such emails.</p>
                <h3>Deleting Your Information</h3>
                <p>If you want us to delete your Personal Information and your account, please contact us at support@storyplace.com&nbsp; with your request.&nbsp; We will take steps to delete your information as soon as we can, but some information may remain in archived/backup copies for our records or as otherwise required by law.</p>
                <h3>Accessing Your Personal Information</h3>
                <p>Registered users of our Services can access their profile information in their settings and update such information.</p>
                <p>Personal Information Retention</p>
                <p>We retain the Personal Information we receive as described in this Privacy Policy for as long as you use our Services or as necessary to fulfill the purpose(s) for which it was collected, provide our Services, resolve disputes, establish legal defenses, conduct audits, pursue legitimate business purposes, enforce our agreements, and comply with applicable laws.</p>
                <p>Links to Other Sites</p>
                <p>If you follow any links that direct you away from the Site, including links to social media sites or to sites for payment options, among others, this Privacy Policy will not apply to your activity on the other Sites you visit. We do not control the privacy policies or the privacy practices of any third parties.&nbsp;</p>
                <p>Privacy in Submitted Materials and User Content</p>
                <p>If you submit any content to us or share such content with other users you must abide by the <a href="https://storyplacestudio.com/terms/" target="_blank" rel="noopener noreferrer">Terms of Use</a> for conditions relating to such materials.&nbsp; We will never ask you to submit any sensitive Personal Information, such as information related to racial or ethnic origin, political opinions, religion or other beliefs; health, biometric or genetic information; or other potentially sensitive information.&nbsp; We ask you to use caution you in submitting information through the Services.</p>
                <p>Security Policy</p>
                <p>We take commercially reasonable steps to protect our customers&rsquo; Personal Information against unauthorized disclosure or loss.&nbsp; However, no data transmission over the Internet can be guaranteed to be 100% secure.&nbsp; Therefore, while we strive to protect user information we cannot ensure or warrant the security of any information you transmit to us or from the Site.&nbsp; You engage in such transmissions at your risk.</p>
                <p>If you believe your Personal Information is being improperly used by us or any third party, please immediately notify us via email at support@storyplace.com.</p>
                <p>Children Under 13</p>
                <p>This Site is restricted to the use of individuals at least 16 years old and of legal age to form a binding contract in their place of residence.&nbsp; No portion of the Site is directed to children under the age of 13.&nbsp; Consequently, we do not knowingly collect personal identifying information from any person we know is a child under the age of 13.&nbsp; If we learn that we have collected personal information from a child under age 13 we will delete that information as quickly as possible.&nbsp; If you are a parent or guardian of a child under 13 years of age and you believe your child has provided us with Personal Information, please contact us at support@storyplace.com.</p>
                <h3>Your California Privacy Rights</h3>
                <p>The following section pertains to the rights of individuals or households in California (&ldquo;California consumers&rdquo;).&nbsp;</p>
                <ul>
                    <li><em>Civil Code Section 1798.83</em></li>
                </ul>
                <p>Under certain circumstances, California Civil Code Section 1798.83 states that, upon receipt of a request by a California consumer, a business may be required to provide detailed information regarding how that business has shared that customer&rsquo;s Personal Information with third parties for direct marking purposes. However, the foregoing does not apply to businesses like ours that do not disclose Personal Information to third parties for direct marketing purposes without prior approval or give customers a free mechanism to opt out of having their Personal Information disclosed to third parties for their direct marketing purposes.</p>
                <ul>
                    <li><em>Rights under the CCPA</em></li>
                </ul>
                <p>As of January 1, 2020, the CCPA (California Civil Code Section 1798.100 <em>et seq.</em>) will provide California consumers with additional rights regarding Personal Information that identifies, relates to, describes, is capable of being associated with, or could reasonably be linked, directly or indirectly with a particular consumer or household. The categories of Personal Information we collect are generally described above but differ for individual consumers depending on the Services used by such consumers.</p>
                <p>Under the CCPA, qualifying California consumers may have the following rights:</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Right to Know and Right to Delete</strong></span><strong>.</strong></p>
                <p>A California consumer has the right to request that we disclose what Personal Information we collect, use, disclose and sell. A California consumer also has the right to submit requests to delete Personal Information.</p>
                <p>When we receive a request to know or delete from a California consumer, we will confirm receipt of the request within 10 days and provide information about how we will process the request, including our verification process. We will respond to such requests within 45 days.</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Right for Disclosure of Information</strong></span><strong>.</strong></p>
                <p>A California consumer may also submit requests that we disclose specific types or categories of Personal Information that we collect.</p>
                <p>Under certain circumstances, we will not provide such information, including where the disclosure creates a substantial, articulable and unreasonable risk to the security of that Personal Information, customers&rsquo; account with us, or the security of our systems or networks. We also will not disclose California consumers&rsquo; social security numbers, driver&rsquo;s license numbers or other government-issued identification numbers, financial account numbers, any health insurance or medical identification numbers, or account passwords and security questions and answers.</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Submitting Requests</strong></span></p>
                <p>If you are a California consumer and would like to make any requests under the CCPA, please direct them as follows:</p>
                <p>StoryPlace, Inc., attention: StoryPlace HQ, Privacy Compliance</p>
                <p>450 N Palm Dr.</p>
                <p>Beverly Hills, CA 90210</p>
                <p>support@storyplace.com</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Verifying Requests</strong></span></p>
                <p>If we receive any request we will use a two-step process for online requests where the California consumer must first, clearly submit the request and then second, separately confirm the request. We will use other appropriate measures to verify requests received by mail or telephone.</p>
                <p>In submitting a request, a California consumer must provide sufficient information to identify the consumer, such as name, e-mail address, home or work address, or other such information that is on record with us so that we can match such information to the Personal Information that we maintain. <span style={{ textDecoration: 'underline' }}>Do not provide social security numbers, driver&rsquo;s license numbers, account numbers,credit or debit card numbers, medical information or health information with requests</span>. If requests are unclear or submitted through means other than outlined above, we will provide the California consumer with specific directions on how to submit the request or remedy any deficiencies. If we cannot verify the identity of the requestor, we may deny the request.</p>
                <p><strong>California Do Not Track Disclosures</strong></p>
                <p>Although some browsers currently offer a &ldquo;do not track (&lsquo;DNT&rsquo;) option,&rdquo; no common industry standard for DNT exists. We therefore do not currently commit to responding to browsers&rsquo; DNT signals.</p>
                <p><strong>Your Rights and Obligations&nbsp;</strong></p>
                <p>We ask that you keep the Personal Information that you provide to us current and that you correct any information you have provided us by contacting us at support@storyplace.com<em>.&nbsp; </em>You represent and warrant that all Personal Information you provide us is true and correct and relates to you and not to any other person.&nbsp;</p>
                <p>If you are a resident of the EEA and wish to access or correct the Personal Information that StoryPlace has about you or have any questions relating to the processing of your Personal Information, please contact us at support@storyplace.com with the subject line &ldquo;GDPR Data.&rdquo;&nbsp;</p>
                <p>If you use the Site, you are responsible for maintaining the confidentiality of your account and for restricting access to your computer or device, and you agree to accept responsibility for all activities that occur under your account.&nbsp;</p>
            </LegalContainer>

        </>

    )
}


export default Terms;