/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next"
import LegalContainer from "../components/legal-container";
import { useRouter } from "next/router";

const Terms: NextPage = () => {

    const router = useRouter()

    const language = router.locale;


    if (language == 'espanol') {
        return (
            <>
                <LegalContainer>
                    <h2>Política de privacidad</h2>

                    <p>StoryPlace, Inc. (&laquo;StoryPlace&raquo;, &laquo;nosotros&raquo;, &laquo;nos&raquo;) respeta la naturaleza confidencial de cualquier informaci&oacute;n personal que nos proporcione. Hemos creado esta Pol&iacute;tica de privacidad para demostrar nuestro compromiso con la privacidad de quienes utilizan nuestras aplicaciones m&oacute;viles,&nbsp;<a href="http://www.storyplace.com/">www.StoryPlace.com</a>, as&iacute; como una serie de servicios relacionados (nuestros &laquo;Servicios&raquo;). Esta Pol&iacute;tica de privacidad describe nuestras pr&aacute;cticas de recopilaci&oacute;n, almacenamiento y divulgaci&oacute;n de informaci&oacute;n y las opciones que tiene con respecto a la forma en que nosotros y nuestros proveedores de comercio electr&oacute;nico recopilamos y utilizamos su informaci&oacute;n personal. Al acceder y utilizar nuestros Servicios, usted acepta la recopilaci&oacute;n, el uso y la divulgaci&oacute;n de informaci&oacute;n a trav&eacute;s de nuestros Servicios, tal como se describe en esta Pol&iacute;tica de privacidad.&nbsp;</p>
                    <p>Los residentes del Espacio Econ&oacute;mico Europeo (&laquo;EEE&raquo;), que incluye a los estados miembros de la Uni&oacute;n Europea (&laquo;UE&raquo;), deben consultar las secciones de esta pol&iacute;tica relacionadas con los &laquo;Derechos de los residentes del EEE&raquo; y &laquo;Transferencias internacionales de datos&raquo; para conocer las disposiciones que pueden aplicarse a ellos.</p>
                    <p>Los residentes de California deben consultar la secci&oacute;n titulada &laquo;Sus derechos de privacidad en California&raquo; para conocer los derechos que se les aplican.</p>
                    <p>Nos reservamos el derecho de cambiar esta Pol&iacute;tica de privacidad en cualquier momento. En caso de que realicemos cambios en esta Pol&iacute;tica de privacidad, dicha pol&iacute;tica se volver&aacute; a publicar en la secci&oacute;n &laquo;Privacidad&raquo; de nuestros sitios web o aplicaciones con la fecha en que se realizaron dichas modificaciones en la parte superior de la p&aacute;gina o podemos ponernos en contacto con usted para informarle sobre las revisiones mediante un enlace a la Pol&iacute;tica de privacidad revisada. Todos los cambios entrar&aacute;n en vigor en la fecha que figura en la parte superior de esta p&aacute;gina y se aplicar&aacute;n a toda la informaci&oacute;n que tengamos sobre usted. El uso continuo de nuestros Servicios despu&eacute;s de la publicaci&oacute;n de cualquier cambio indica que acepta los cambios y que contin&uacute;a dando tu consentimiento a que procesemos su Informaci&oacute;n Personal. Si en alg&uacute;n momento no est&aacute; de acuerdo con alguna parte de la Pol&iacute;tica de privacidad en vigor debe dejar de utilizar nuestros Servicios de inmediato. Dado que esta Pol&iacute;tica de privacidad contiene obligaciones legales, le recomendamos que la revise detenidamente. Si tiene alguna pregunta sobre esta Pol&iacute;tica de privacidad o nuestras pr&aacute;cticas de recopilaci&oacute;n, almacenamiento y divulgaci&oacute;n de informaci&oacute;n, p&oacute;ngase en contacto con nosotros en support@storyplace.com o env&iacute;enos un correo a StoryPlace, Inc., StoryPlace HQ, 450 N Palm Dr., Beverly Hills, CA 90210.&nbsp;</p>
                    <p>Informaci&oacute;n personal que recopilamos y c&oacute;mo la utilizamos</p>
                    <p>StoryPlace recopila informaci&oacute;n personal sobre usted cuando utiliza nuestros Servicios. La &laquo;Informaci&oacute;n Personal&raquo; es la informaci&oacute;n que puede usarse para identificarlo directa o indirectamente, como su nombre, seud&oacute;nimo, direcci&oacute;n de correo electr&oacute;nico, direcci&oacute;n f&iacute;sica, n&uacute;mero de tel&eacute;fono u otra informaci&oacute;n sobre usted. La mayor&iacute;a de esta informaci&oacute;n personal se recopila cuando se registra para utilizar nuestras aplicaciones, sitio web o StoryPlace studio, utiliza nuestros Servicios, incluida la suscripci&oacute;n, solicita informaci&oacute;n o actualizaciones o nos proporciona su informaci&oacute;n de contacto de otro modo. Tambi&eacute;n puede a&ntilde;adir detalles a su perfil, como una foto de perfil, informaci&oacute;n biogr&aacute;fica y otra Informaci&oacute;n Personal. Parte de esta Informaci&oacute;n Personal ser&aacute; necesaria si desea participar en los Servicios que ofrecemos, incluido el uso de la aplicaci&oacute;n.</p>
                    <p>En general, el tipo de informaci&oacute;n personal que recopilamos incluye, pero no se limita a:</p>
                    <ul>
                        <li>
                            <p>Informaci&oacute;n personal para ponernos en contacto con usted en relaci&oacute;n con nuestros Servicios o asuntos de inter&eacute;s;</p>
                        </li>
                        <li>
                            <p>Informaci&oacute;n personal necesaria para utilizar los Servicios que ha solicitado, incluida la creaci&oacute;n de una cuenta y la suscripci&oacute;n a los Servicios;</p>
                        </li>
                        <li>
                            <p>Informaci&oacute;n personal no identificable y agregada relacionada con sus visitas a nuestros sitios web o aplicaciones que nos ayuda a mantener las caracter&iacute;sticas, la funcionalidad y la experiencia de usuario adecuadas</p>
                        </li>
                    </ul>
                    <p>Nuestro proveedor de comercio electr&oacute;nico y nosotros utilizamos esos datos para: (i) permitirle iniciar sesi&oacute;n para utilizar los Servicios; (ii) permitirle suscribirse a nuestros Servicios; (iii) protegerlo contra posibles fraudes; (iv) ponernos en contacto con usted si hay alg&uacute;n problema con su cuenta; (v) responder a sus consultas o preguntas; y (vi) mantener una comunicaci&oacute;n regular con usted seg&uacute;n sea necesario para informarle de ofertas, actualizaciones y otra informaci&oacute;n sobre StoryPlace y nuestros Servicios.</p>
                    <h3>Redes sociales</h3>
                    <p>Si decide conectarse con nosotros a trav&eacute;s de una red social de terceros, como Facebook, Twitter, Instagram y otras redes (cada una de ellas, una &laquo;red social&raquo;), podemos recopilar informaci&oacute;n personal de su perfil en dicha red social, como su nombre, nombre de usuario y direcci&oacute;n de correo electr&oacute;nico. Adem&aacute;s, nuestras aplicaciones m&oacute;viles ofrecen funciones que le permitir&aacute;n compartir informaci&oacute;n de nuestras aplicaciones m&oacute;viles en una red social o compartir informaci&oacute;n de nuestros sitios de redes sociales. Si decide utilizar dichas funciones, es posible que permitan compartir y recopilar informaci&oacute;n hacia y desde dicha red social, por lo que debe comprobar la pol&iacute;tica de privacidad de cada red social antes de utilizar dichas funciones.</p>
                    <h3>Datos no identificables e informaci&oacute;n personal agregada</h3>
                    <p>Independientemente de si se registra para obtener una cuenta o nos env&iacute;a informaci&oacute;n, StoryPlace y los terceros que nos prestan servicios de comercio electr&oacute;nico pueden enviar una o m&aacute;s &laquo;cookies&raquo; a su ordenador. Las cookies son peque&ntilde;os archivos de texto que se colocan en su navegador web cuando visita nuestro Sitio y que almacenan informaci&oacute;n en su computadora, como sus preferencias de sitio. Usamos cookies cuando inicia sesi&oacute;n para realizar un seguimiento de su sesi&oacute;n personal. Tambi&eacute;n utilizamos cookies para rastrear su actividad en el sitio como persona &uacute;nica. Por motivos de seguridad, toda esta informaci&oacute;n se almacena de forma cifrada. Estos datos se pueden utilizar para mostrar informaci&oacute;n sobre nuestros Servicios en sitios web operados por terceros.</p>
                    <p>Puede configurar su navegador web para que le informe cuando se configuran las cookies o para evitar que se establezcan cookies por completo. Sin embargo, tenga en cuenta que si rechaza el uso de cookies, es posible que experimente una funcionalidad reducida y tiempos de respuesta del sitio m&aacute;s lentos.</p>
                    <p>StoryPlace o nuestros proveedores de servicios, incluidos FireBase, Google Analytics y Apple Develop App Analytics, tambi&eacute;n pueden recopilar datos de navegaci&oacute;n web relacionados con el uso de nuestro sitio web. Dicha informaci&oacute;n puede incluir: su direcci&oacute;n de protocolo de Internet (IP), el tipo de navegador y el proveedor de servicios de Internet (ISP); su sistema operativo; las p&aacute;ginas de nuestras p&aacute;ginas web a las que accede y con qu&eacute; frecuencia accede a ellas; las p&aacute;ginas de referencia o de salida; los datos del flujo de clics; y las fechas y horas en las que visita los sitios web. Estos datos pueden recopilarse mediante cookies, balizas web, etiquetas de p&aacute;gina o herramientas similares. Al igual que ocurre con las cookies, la informaci&oacute;n de navegaci&oacute;n web es an&oacute;nima, es decir, datos transaccionales de &laquo;flujo de clics&raquo; que no se asocian a ning&uacute;n usuario como individuo.</p>
                    <p>Los datos de navegaci&oacute;n web e informaci&oacute;n similar pueden agregarse o anonimizarse con fines administrativos. StoryPlace puede, por ejemplo, utilizar esta informaci&oacute;n agregada en la administraci&oacute;n de nuestro sitio web para mejorar su usabilidad y evaluar el &eacute;xito de determinadas campa&ntilde;as de marketing y publicidad, estrategias de optimizaci&oacute;n de motores de b&uacute;squeda y otras actividades de marketing. Tambi&eacute;n lo utilizamos para ayudar a optimizar el sitio web en funci&oacute;n de las necesidades de nuestros usuarios.</p>
                    <h3>C&oacute;mo y cu&aacute;ndo se comparte su informaci&oacute;n con otras partes</h3>
                    <p>StoryPlace no vende, comercializa ni otorga licencias de informaci&oacute;n personal sobre sus usuarios con fines de marketing. Sin embargo, trabajamos con varios socios de confianza que desempe&ntilde;an funciones vitales como parte de nuestras operaciones, incluido el procesamiento de los pagos de las suscripciones. No compartimos su informaci&oacute;n personal a menos que sea necesario para cumplir con nuestras responsabilidades, incluido el suministro de informaci&oacute;n o prestaci&oacute;n de servicios.&nbsp;</p>
                    <p>Como parte de nuestra misi&oacute;n de recordar a las personas que cada quien tiene una historia que contar y que cada historia tiene una lecci&oacute;n que ense&ntilde;ar, podemos compartir su seud&oacute;nimo o historias y la informaci&oacute;n de ubicaci&oacute;n asociada a sus historias fuera de nuestras aplicaciones m&oacute;viles. Por ejemplo, podemos compartir esta informaci&oacute;n en nuestros sitios web p&uacute;blicos o en nuestros materiales promocionales para animar a otros usuarios a compartir sus Historias y promover una cultura de Historias en todo el mundo. Tenga en cuenta que los derechos de StoryPlace sobre las Historias que comparte en StoryPlace se establecen en las&nbsp;<a href="https://storyplacestudio.com/terms/">T&eacute;rminos de uso</a>.</p>
                    <h3>Intercambio adicional de informaci&oacute;n</h3>
                    <p>Podemos contratar a terceros para que nos ayuden a llevar a cabo otras funciones internas, como el procesamiento de suscripciones, los servicios al cliente u otras recopilaciones de datos relevantes para nuestro negocio. La informaci&oacute;n personal se comparte con estos terceros solo en la medida necesaria para que podamos procesar las transacciones que usted inicie o prestar otros servicios espec&iacute;ficos. Nuestros socios est&aacute;n obligados legalmente a mantener su informaci&oacute;n personal privada y segura.</p>
                    <p>Podemos compartir su informaci&oacute;n personal con las fuerzas del orden u otras agencias gubernamentales seg&uacute;n lo exija la ley o con el fin de limitar el fraude. Nos reservamos el derecho de divulgar su informaci&oacute;n personal cuando consideremos que la divulgaci&oacute;n es necesaria para proteger nuestros derechos o para cumplir con un procedimiento judicial, una orden judicial o un proceso legal. Adem&aacute;s, nos reservamos el derecho de divulgar su Informaci&oacute;n personal que consideremos, de buena fe, apropiada o necesaria para tomar precauciones contra la responsabilidad, investigar y defendernos de cualquier demanda o denuncia de terceros, ayudar a los organismos gubernamentales encargados de hacer cumplir la ley, proteger la seguridad o la integridad del Sitio o nuestros servicios o proteger los derechos, la propiedad o la seguridad personal de StoryPlace, sus usuarios, emisores u otros.</p>
                    <p>No compartiremos su Informaci&oacute;n personal si dicha divulgaci&oacute;n est&aacute; prohibida por la ley de privacidad y protecci&oacute;n de datos aplicable, incluido, entre otros, el Reglamento general de protecci&oacute;n de datos del EEE en vigor desde el 25 de mayo de 2018.</p>
                    <h3>Residentes del EEE</h3>
                    <p>Esta secci&oacute;n de la Pol&iacute;tica de privacidad se aplica a los residentes del Espacio Econ&oacute;mico Europeo (&laquo;EEE&raquo;). El EEE est&aacute; formado por los estados miembros de la Uni&oacute;n Europea, es decir, Austria, B&eacute;lgica, Bulgaria, Croacia, Rep&uacute;blica de Chipre, Rep&uacute;blica Checa, Dinamarca, Estonia, Finlandia, Francia, Alemania, Grecia, Hungr&iacute;a, Irlanda, Italia, Letonia, Lituania, Luxemburgo, Malta, Pa&iacute;ses Bajos, Polonia, Portugal, Ruman&iacute;a, Eslovaquia, Eslovenia, Espa&ntilde;a, Suecia y el Reino Unido, e Islandia, Liechtenstein y Noruega. Esta secci&oacute;n tambi&eacute;n se aplica a los residentes de Suiza y, en caso de su salida de la UE, a los residentes del Reino Unido (que, tras el Brexit, pasa a estar bajo la jurisdicci&oacute;n del Reglamento General de Protecci&oacute;n de Datos del Reino Unido (&laquo;RGPD del Reino Unido&raquo;), el cual StoryPlace sigue respetando). &nbsp;Los residentes del EEE y Suiza se denominan aqu&iacute; &laquo;residentes del EEE&raquo;.</p>
                    <p>A partir del 25 de mayo de 2018, StoryPlace realizar&aacute; todo el procesamiento de la informaci&oacute;n personal de los residentes del EEE de conformidad con el Reglamento general de protecci&oacute;n de datos (2016/679) del Parlamento Europeo y del Consejo, del 27 de abril de 2016, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al procesamiento de la informaci&oacute;n personal y a la libre circulaci&oacute;n de dichos datos (&laquo;RGPD&raquo;).</p>
                    <p>Seg&uacute;n el RGPD y el RGPD del Reino Unido, StoryPlace es tanto el controlador como el coprocesador de la Informaci&oacute;n Personal de los residentes del EEE. El prop&oacute;sito de StoryPlace al recopilar y procesar la Informaci&oacute;n Personal de los residentes del EEE es autenticar la suscripci&oacute;n a nuestras listas de correo y nuestros Servicios. La base legal para recopilar Informaci&oacute;n Personal para suscribirse a nuestras listas de correo electr&oacute;nico y Servicios es su consentimiento, incluso durante el proceso de suscripci&oacute;n. Puede retirar su consentimiento para recibir dichas comunicaciones siguiendo las instrucciones para &laquo;Darse de baja&raquo; que figuran en cualquier comunicaci&oacute;n o poni&eacute;ndose en contacto con nosotros en support@storyplace.com.</p>
                    <p>Usamos Stripe para procesar las suscripciones, incluso para los residentes del EEE.</p>
                    <p>Los residentes del EEE y el Reino Unido pueden obtener informaci&oacute;n sobre la Informaci&oacute;n Personal que StoryPlace tiene sobre ellos poni&eacute;ndose en contacto con StoryPlace en support@storyplace.com.</p>
                    <h3>Transferencias internacionales de datos</h3>
                    <p>Si reside fuera de los Estados Unidos, incluso en el EEE, transferimos la informaci&oacute;n personal que nos haya proporcionado para su procesamiento en los Estados Unidos. Seg&uacute;n el RGPD y el RGPD del Reino Unido, StoryPlace es considerado un &laquo;controlador&raquo; y un &laquo;coprocesador&raquo; de la informaci&oacute;n personal de los residentes del EEE y de Reino Unido. Al proporcionar informaci&oacute;n personal a StoryPlace con el fin de obtener los Servicios, usted acepta el procesamiento de dichos datos en los Estados Unidos. La transferencia de su informaci&oacute;n personal a los Estados Unidos es necesaria para la ejecuci&oacute;n de un contrato entre usted y StoryPlace para obtener los Servicios.&nbsp;</p>
                    <p>Tenga en cuenta que los Estados Unidos no tienen leyes de protecci&oacute;n de datos equivalentes a las del EEE y otras jurisdicciones.</p>
                    <h3>Comunicaciones relacionadas con nuestros servicios</h3>
                    <p>Le enviaremos notificaciones por correo electr&oacute;nico y boletines informativos gratuitos de vez en cuando con ofertas, sugerencias y otra informaci&oacute;n. Algunas notificaciones son comunicaciones relacionadas con nosotros y nuestros Servicios. Puede optar no recibir dichas comunicaciones siguiendo las instrucciones de &laquo;cancelaci&oacute;n de suscripci&oacute;n&raquo; que se proporcionan en el correo electr&oacute;nico.&nbsp;</p>
                    <h3>Comunicaciones legales o de seguridad</h3>
                    <p>Tambi&eacute;n enviamos avisos que son necesarios por motivos legales o de seguridad. Por ejemplo, ciertas notificaciones se env&iacute;an para su propia protecci&oacute;n. En otros casos, estas notificaciones implican cambios en varios acuerdos legales, como la Pol&iacute;tica de privacidad o las T&eacute;rminos de uso. Por lo general, no puede optar por no recibir dichos correos electr&oacute;nicos, y el env&iacute;o de dichas actualizaciones no anula su obligaci&oacute;n de informarse sobre las &uacute;ltimas actualizaciones y los diversos t&eacute;rminos y condiciones que aplicamos a nuestros usuarios.</p>
                    <h3>Comunicaciones sobre cuentas y pedidos</h3>
                    <p>Si se suscribe a nuestros Servicios, podemos enviarle comunicaciones relacionadas con dichos Servicios. Tambi&eacute;n podemos enviar comunicaciones para brindar atenci&oacute;n al cliente o respuestas a preguntas sobre el funcionamiento de los Servicios. Por lo general, no puede optar por no recibir dichos correos electr&oacute;nicos.</p>
                    <h3>Eliminaci&oacute;n de su informaci&oacute;n</h3>
                    <p>Si desea que eliminemos su Informaci&oacute;n personal y su cuenta, p&oacute;ngase en contacto con nosotros en support@storyplace.com con su solicitud. Tomaremos medidas para eliminar su informaci&oacute;n lo antes posible, pero es posible que parte de la informaci&oacute;n permanezca en copias archivadas o de respaldo para nuestros registros o seg&uacute;n lo exija la ley.</p>
                    <h3>Acceso a su informaci&oacute;n personal</h3>
                    <p>Los usuarios registrados de nuestros Servicios pueden acceder a la informaci&oacute;n de su perfil en su configuraci&oacute;n y actualizar dicha informaci&oacute;n.</p>
                    <p><br /></p>
                    <p>Retenci&oacute;n de informaci&oacute;n personal</p>
                    <p>Conservamos la Informaci&oacute;n personal que recibimos tal como se describe en esta Pol&iacute;tica de privacidad durante el tiempo que utilice nuestros Servicios o seg&uacute;n sea necesario para cumplir con los fines para los que se recopil&oacute;, prestar nuestros Servicios, resolver disputas, establecer defensas legales, realizar auditor&iacute;as, perseguir fines comerciales leg&iacute;timos, hacer cumplir nuestros acuerdos y cumplir con las leyes aplicables.</p>
                    <p>Enlaces a otros sitios</p>
                    <p>Si sigue alg&uacute;n enlace que lo dirija fuera de nuestro Sitio, incluidos enlaces a sitios de redes sociales o sitios con opciones de pago, entre otros, esta Pol&iacute;tica de privacidad no se aplicar&aacute; a su actividad en los otros sitios que visite. No controlamos las pol&iacute;ticas de privacidad ni las pr&aacute;cticas de privacidad de terceros, ni tampoco ellos las nuestras.&nbsp;</p>
                    <p><br /></p>
                    <p>Privacidad en los materiales enviados y en el contenido del usuario</p>
                    <p>Si nos env&iacute;a alg&uacute;n contenido o lo comparte con otros usuarios, debe cumplir con los&nbsp;<a href="https://storyplacestudio.com/terms/">T&eacute;rminos de uso</a> de las condiciones relacionadas con dichos materiales. Nunca le pediremos que env&iacute;e ninguna informaci&oacute;n personal confidencial, como informaci&oacute;n relacionada con el origen racial o &eacute;tnico, opiniones pol&iacute;ticas, religi&oacute;n u otras creencias; informaci&oacute;n de salud, biom&eacute;trica o gen&eacute;tica; u otra informaci&oacute;n potencialmente confidencial. Le pedimos que tenga cuidado al enviar informaci&oacute;n a trav&eacute;s de los Servicios.</p>
                    <p>Pol&iacute;tica de seguridad</p>
                    <p>Tomamos medidas comercialmente razonables para proteger la informaci&oacute;n personal de nuestros clientes contra la divulgaci&oacute;n o p&eacute;rdida no autorizadas. Sin embargo, no se puede garantizar que ninguna transmisi&oacute;n de datos a trav&eacute;s de Internet sea 100% segura. Por lo tanto, si bien nos esforzamos por proteger la informaci&oacute;n del usuario, no podemos garantizar la seguridad de la informaci&oacute;n que nos transmita o que se transmita desde el Sitio. Usted realiza dichas transmisiones por su cuenta y riesgo.</p>
                    <p>Si cree que nosotros o nuestros usuarios est&aacute;n utilizando su informaci&oacute;n personal de forma indebida, notif&iacute;quenos inmediatamente por correo electr&oacute;nico a support@storyplace.com.</p>
                    <p>Ni&ntilde;os menores de 13 a&ntilde;os</p>
                    <p>Este sitio est&aacute; restringido al uso de personas mayores de 13 a&ntilde;os y mayores de edad para celebrar un contrato vinculante en su lugar de residencia. Ninguna parte del Sitio est&aacute; dirigida a ni&ntilde;os menores de 13 a&ntilde;os. En consecuencia, no recopilamos a sabiendas informaci&oacute;n de identificaci&oacute;n personal de ninguna persona que sepamos que es un ni&ntilde;o menor de 13 a&ntilde;os. Si nos enteramos de que hemos recopilado informaci&oacute;n personal de un ni&ntilde;o menor de 13 a&ntilde;os, eliminaremos esa informaci&oacute;n lo antes posible. Si es padre o tutor de un ni&ntilde;o menor de 13 a&ntilde;os y cree que su hijo nos ha proporcionado informaci&oacute;n personal, p&oacute;ngase en contacto con nosotros en support@storyplace.com.</p>
                    <h3>Sus derechos de privacidad en California</h3>
                    <p>La siguiente secci&oacute;n se refiere a los derechos de las personas u hogares en California (&laquo;consumidores de California&raquo;).&nbsp;</p>
                    <ul>
                        <li>
                            <p>Art&iacute;culo 1798.83 del C&oacute;digo Civil,&nbsp;</p>
                        </li>
                    </ul>
                    <p>En determinadas circunstancias, el art&iacute;culo 1798.83 del C&oacute;digo Civil de California establece que, al recibir una solicitud de un consumidor de California, se le puede exigir a una empresa que proporcione informaci&oacute;n detallada sobre la forma en que esa empresa ha compartido la Informaci&oacute;n Personal de ese cliente con terceros para fines de marketing directo. Sin embargo, lo anterior no se aplica a empresas como la nuestra, que no divulgan Informaci&oacute;n Personal a terceros con fines de marketing directo sin aprobaci&oacute;n previa ni ofrecen a los clientes un mecanismo gratuito para optar por que su informaci&oacute;n personal no se divulgue a terceros con fines de marketing directo.</p>
                    <ul>
                        <li>
                            <p>Derechos en virtud de la CCPA</p>
                        </li>
                    </ul>
                    <p>A partir del 1 de enero de 2020, la CCPA (art&iacute;culo 1798.100 y siguientes del C&oacute;digo Civil de California) otorgar&aacute; a los consumidores de California derechos adicionales con respecto a la Informaci&oacute;n personal que identifique, se relacione con, describa, pueda asociarse o pueda vincularse de manera razonable, directa o indirectamente con un consumidor u hogar en particular. Las categor&iacute;as de Informaci&oacute;n personal que recopilamos se describen en general previamente, pero var&iacute;an seg&uacute;n los consumidores individuales en funci&oacute;n de los Servicios que utilicen dichos consumidores.</p>
                    <p>Seg&uacute;n la CCPA, los consumidores de California que re&uacute;nan los requisitos pueden tener los siguientes derechos:</p>
                    <p>Derecho a saber y derecho a eliminar.</p>
                    <p>Un consumidor de California tiene derecho a solicitar que revelemos qu&eacute; informaci&oacute;n personal recopilamos, utilizamos, divulgamos y vendemos. Un consumidor de California tambi&eacute;n tiene derecho a enviar solicitudes para eliminar informaci&oacute;n personal.</p>
                    <p>Cuando recibamos una solicitud de informaci&oacute;n o eliminaci&oacute;n de un consumidor de California, confirmaremos la recepci&oacute;n de la solicitud en un plazo de 10 d&iacute;as y proporcionaremos informaci&oacute;n sobre c&oacute;mo procesaremos la solicitud, incluido nuestro proceso de verificaci&oacute;n. Responderemos a dichas solicitudes en un plazo de 45 d&iacute;as.</p>
                    <p>Derecho a la divulgaci&oacute;n de informaci&oacute;n.</p>
                    <p>Un consumidor de California tambi&eacute;n puede solicitar que divulguemos tipos o categor&iacute;as espec&iacute;ficas de informaci&oacute;n personal que recopilamos.</p>
                    <p>En determinadas circunstancias, no proporcionaremos dicha informaci&oacute;n, incluso cuando la divulgaci&oacute;n genere un riesgo sustancial, articulable e irrazonable para la seguridad de esa informaci&oacute;n personal, la cuenta de los clientes que tienen con nosotros o la seguridad de nuestros sistemas o redes. Tampoco divulgaremos los n&uacute;meros de seguro social, los n&uacute;meros de licencia de conducir u otros n&uacute;meros de identificaci&oacute;n emitidos por el gobierno, los n&uacute;meros de cuentas financieras, ning&uacute;n n&uacute;mero de seguro m&eacute;dico o de identificaci&oacute;n m&eacute;dica, ni las contrase&ntilde;as de las cuentas ni las preguntas y respuestas de seguridad.</p>
                    <p>Env&iacute;o de solicitudes</p>
                    <p>Si es un consumidor de California y desea realizar cualquier solicitud en virtud de la CCPA, dir&iacute;jala de la siguiente manera:</p>
                    <p>StoryPlace, Inc., atenci&oacute;n: StoryPlace HQ, Privacy Compliance</p>
                    <p>450 N Palm Dr.</p>
                    <p>Beverly Hills, CA 90210</p>
                    <p>support@storyplace.com</p>
                    <p>Verificaci&oacute;n de solicitudes</p>
                    <p>Si recibimos alguna solicitud, utilizaremos un proceso de dos pasos para las solicitudes en l&iacute;nea, en el que el consumidor de California primero debe enviar la solicitud de manera clara y, luego, confirmarla por separado. Utilizaremos otras medidas apropiadas para verificar las solicitudes recibidas por correo o por tel&eacute;fono.</p>
                    <p>Al presentar una solicitud, un consumidor de California debe proporcionar informaci&oacute;n suficiente para identificarlo, como su nombre, direcci&oacute;n de correo electr&oacute;nico, direcci&oacute;n de casa o trabajo, u otra informaci&oacute;n similar que conste en nuestro registro, de modo que podamos hacer coincidir dicha informaci&oacute;n con la Informaci&oacute;n Personal que conservamos.&nbsp;No proporcione n&uacute;meros de seguro social, n&uacute;meros de licencia de conducir, n&uacute;meros de cuenta, n&uacute;meros de tarjetas de cr&eacute;dito o d&eacute;bito, informaci&oacute;n m&eacute;dica o informaci&oacute;n de salud junto con las solicitudes. Si las solicitudes no est&aacute;n claras o se presentan por medios distintos a los descritos anteriormente, proporcionaremos al consumidor de California instrucciones espec&iacute;ficas sobre c&oacute;mo presentar la solicitud o corregir cualquier deficiencia. Si no podemos verificar la identidad del solicitante, podemos denegar la solicitud.</p>
                    <p>Divulgaciones Do Not Track (&laquo;no rastrear&raquo;) de California</p>
                    <p>Si bien algunos navegadores ofrecen actualmente la opci&oacute;n de &laquo;no rastrear (&apos;DNT&apos;)&raquo;, no existe un est&aacute;ndar industrial com&uacute;n para el DNT. Por lo tanto, actualmente no nos comprometemos a responder a las se&ntilde;ales DNT de los navegadores.</p>
                    <p>Sus derechos y obligaciones&nbsp;</p>
                    <p>Le pedimos que mantenga actualizada la informaci&oacute;n personal que nos proporciona y que corrija cualquier informaci&oacute;n que nos haya proporcionado poni&eacute;ndose en contacto con nosotros en support@storyplace.com.&nbsp;Usted declara y garantiza que toda la informaci&oacute;n personal que nos proporciona es verdadera y correcta y se refiere a usted y no a ninguna otra persona.&nbsp;</p>
                    <p>Si reside en el EEE y desea acceder o corregir la informaci&oacute;n personal que StoryPlace tiene sobre usted o tiene alguna pregunta relacionada con el procesamiento de su informaci&oacute;n personal, p&oacute;ngase en contacto con nosotros en support@storyplace.com con el asunto &laquo;Datos RGPD&raquo;.&nbsp;</p>
                    <p>Si utiliza el Sitio, es responsable de mantener la confidencialidad de su cuenta y de restringir el acceso a su computadora o dispositivo, y acepta la responsabilidad de todas las actividades que ocurran en su cuenta.&nbsp;</p>

                </LegalContainer>
            </>
        )
    }

    return (
        <>
            <LegalContainer>

                <h2 >Privacy Policy</h2>
                <p>StoryPlace, Inc. (&ldquo;StoryPlace,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) respects the sensitive nature of any personal information you provide to us.&nbsp; We have created this Privacy Policy in order to demonstrate our commitment to the privacy of those who use our mobile applications, <a href="http://www.storyplace.com/" target="_blank" rel="noopener noreferrer">www.Storyplace.com</a>, as well as a number of related services (our &ldquo;Services&rdquo;). This Privacy Policy describes our information collection, storage and disclosure practices and the choices you have regarding how your personal information is collected and used by us and our e-commerce providers.&nbsp; By accessing and using our Services, you consent to the collection, use and disclosure of information through our Services as described in this Privacy Policy.&nbsp;</p>
                <p>Residents of the European Economic Area (&ldquo;EEA&rdquo;), which includes the member states of the European Union (&ldquo;EU&rdquo;), should consult the sections of this policy relating to the &ldquo;Rights of EEA Residents&rdquo; and &ldquo;International Data Transfers&rdquo; for provisions that may apply to them.</p>
                <p>California residents should consult the section titled &ldquo;Your California Privacy Rights&rdquo; for rights that apply to them.</p>
                <p>We reserve the right to change this Privacy Policy at any time.&nbsp; In the event we make changes to this Privacy Policy, such policy will be re-posted in the &ldquo;Privacy&rdquo; section of our websites or applications with the date such modifications were made indicated on the top of the page or we may contact you to inform you about the revisions with a link to the revised Privacy Policy.&nbsp; All changes are effective on the date listed at the top of this page and will apply to all information that we have about you.&nbsp; Your continued use of our Services after any change is posted indicates your acceptance of the changes and your continued consent to our processing of your Personal Information.&nbsp; If at any point you do not agree to any portion of the Privacy Policy then in effect you should immediately stop using our Services.&nbsp; Because this Privacy Policy contains legal obligations we encourage you to review this Privacy Policy carefully.&nbsp; If you have any questions concerning this Privacy Policy or our information collection, storage and disclosure practices, please contact us at support@storyplace.com or mail us at StoryPlace, Inc., StoryPlace HQ, 450 N Palm Dr., Beverly Hills, CA 90210.</p>
                <p><strong>Personal Information That We Collect and How We Use It</strong></p>
                <p>StoryPlace collects Personal Information about you when you use our Services.&nbsp; &ldquo;Personal Information&rdquo; is information that may be used to directly or indirectly identify you, including your name, Pen Name, e-mail address, physical address, phone number or other information about you.&nbsp; The majority of such Personal Information is collected when you register to use our applications, website or StoryPlace Studio, use our Services, including subscribing, request information or updates or otherwise provide us with your contact information.&nbsp; You may also add details to your profile, such as a profile photo, biographical information and other Personal Information.&nbsp; Some of this Personal Information will be required if you wish to partake in the Services that we provide, including using the application.</p>
                <p>In general, the type of Personal Information we collect includes, but is not limited to:</p>
                <ul>
                    <li>Personal Information to contact you regarding our Services or matters of interest;</li>
                    <li>Personal Information necessary to use the Services that you have requested, including establishing an account and subscribing to the Services;</li>
                    <li>Un-identifiable and aggregated Personal Information pertaining to your visits to our websites or applications that help us maintain the appropriate features, functionality and user experience</li>
                </ul>
                <p>We and our e-commerce provider use that data to: (i) enable you to log in to use the Services; (ii) allow you to subscribe to our Services; (iii) guard against potential fraud; (iv) contact you if there is a problem with your account; (v) provide answers to your inquiries or questions; and (vi) maintain regular communication with you as may be necessary to inform you of offers, updates and other information regarding StoryPlace and our Services.</p>
                <h3>Social Networks</h3>
                <p>If you choose to connect to us through a third-party social network such as Facebook, Twitter, Instagram and other networks (each, a &ldquo;Social Network&rdquo;), we may collect Personal Information from your profile on such Social Network, such as your name, user name, and e-mail address.&nbsp; In addition, our mobile applications offer features that will allow you to share information from our mobile applications to a Social Network or share information from our Social Network sites. &nbsp; If you decide to use such features, they may allow the sharing and collection of information both to and from such Social Network so you should check the privacy policy of each Social Network before using such features.</p>
                <h3>Non-Identifiable Data and Aggregated Personal Information</h3>
                <p>Regardless of whether you register for an account or submit information to us, StoryPlace and third parties performing e-commerce services for us may send one or more "cookies" to your computer.&nbsp; Cookies are small text files placed on your web browser when you visit our Site that store information on your computer, such as your site preferences.&nbsp; We use cookies when you sign in to keep track of your personal session.&nbsp; We also use cookies to track your activity on the site as a unique person.&nbsp; For security purposes, all of this information is stored in encrypted form.&nbsp; This data may be used to display information about our Services on websites operated by third parties.</p>
                <p>You can set your web browser to inform you when cookies are set, or to prevent cookies from being set altogether.&nbsp; Please note, however, that if you decline to use cookies, you may experience reduced functionality and slower site response times.</p>
                <p>StoryPlace or our service providers, including FireBase, Google Analytics and Apple Develop App Analytics, may also collect web surfing data related to your use of our website.&nbsp; Such information may include: your Internet Protocol (IP) address, browser type, and internet service provider (ISP); your operating system; which of our web pages you access and how frequently you access them; referral or exit pages; click stream data; and the dates and times that you visit the websites.&nbsp; This data may be collected using cookies, web beacons, page tags or similar tools.&nbsp; As with cookies, the web surfing information is anonymous, "click stream" transactional data that is not associated with any users as individuals.</p>
                <p>Web surfing data and similar information may be aggregated or anonymized for administrative purposes.&nbsp; StoryPlace may, for example, use this aggregated information in the administration of our website to improve its usability and to evaluate the success of particular marketing and advertising campaigns, search engine optimization strategies, and other marketing activities.&nbsp; We also use it to help optimize the website based on the needs of our users.</p>
                <h3>How and When Your Information Is Shared With Other Parties</h3>
                <p>StoryPlace does not sell, trade or license Personal Information about its users for marketing purposes.&nbsp; We do, however, work with a number of trusted partners who perform vital functions as part of our operations, including processing payments for subscriptions.&nbsp; We do not share your Personal Information unless it is necessary to fulfill our responsibilities, including providing information or Services.&nbsp;</p>
                <p>As part of our mission to remind people that everyone has a story to tell and every story has a lesson to teach, we may share your Pen Name, or stories and the location information associated with your stories outside of our mobile applications.&nbsp; For example, we may share this information on our public websites or in our promotional materials in order to encourage other users to share their Stories and to promote a culture of Stories worldwide.&nbsp; Note that StoryPlace&rsquo;s rights to and in the Stories you share on StoryPlace are set out in the <a href="https://storyplacestudio.com/terms/" target="_blank" rel="noopener noreferrer">Terms of Use</a>.</p>
                <h3>Additional Sharing of Information</h3>
                <p>We may engage third parties to help us carry out certain other internal functions such as subscription processing, client services, or other data collection relevant to our business.&nbsp; Personal Information is shared with these third parties only to the extent necessary for us to process the transactions you initiate or perform other specific services.&nbsp; Our partners are legally required to keep your Personal Information private and secure.</p>
                <p>We may share your Personal Information with law enforcement or other government agencies as required by law or for the purposes of limiting fraud. We reserve the right to disclose your Personal Information when we believe that disclosure is necessary to protect our rights or to comply with a judicial proceeding, court order or legal process. We further reserve the right to disclose any of your Personal Information that we believe, in good faith, appropriate or necessary to take precautions against liability, to investigate and defend against any third-party claims or allegations, to assist government enforcement agencies, to protect the security or integrity of the Site or our services, or to protect the rights, property or personal safety of StoryPlace, its users, issuers, or others.</p>
                <p>We will not share your Personal Information if such sharing is prohibited by applicable privacy and data protection law, including, without limitation, the EEA&rsquo;s General Data Protection Regulation effective May 25, 2018.</p>
                <h3>EEA Residents</h3>
                <p>This section of the Privacy Policy is applicable to residents of the European Economic Area (&ldquo;EEA&rdquo;).&nbsp; The EEA consists of the member states of the European Union, i.e., Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden and the United Kingdom, and Iceland, Liechtenstein, and Norway.&nbsp; This section also applies to residents of Switzerland and, in the event of its departure from the EU, residents of the United Kingdom. &nbsp; Residents of the EEA and Switzerland are referred to here as &ldquo;EEA Residents.&rdquo;</p>
                <p>From May 25, 2018, all processing of Personal Information of EEA Residents is performed by StoryPlace in accordance with the General Data Protection Regulation (2016/679) of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons regarding the processing of Personal Information and on the free movement of such data (&ldquo;GDPR&rdquo;).</p>
                <p>Under the GDPR, StoryPlace is both the controller and a co-processor of the Personal Information of EEA Residents.&nbsp; StoryPlace&rsquo;s purpose for collecting and processing Personal Information from EEA Residents is to authenticate subscription to our mailing lists and our Services. The legal basis for collecting Personal Information for subscribing to our e-mail lists and Services is your consent, including during the subscription process.&nbsp; You may withdraw consent for obtaining such communications by following the &ldquo;Unsubscribe&rdquo; instructions on any communication or by contacting us at support@storyplace.com.</p>
                <p>We use Stripe to process subscriptions, including for EEA Residents.</p>
                <p>EEA Residents may obtain information about the Personal Information that StoryPlace holds about them by contacting StoryPlace at support@storyplace.com.</p>
                <h3>International Data Transfers</h3>
                <p>If you are resident outside the United States, including in the EEA, we transfer Personal Information provided by you for processing in the United States.&nbsp; Under the GDPR, StoryPlace is considered a &ldquo;controller&rdquo; and a &ldquo;co-processor&rdquo; of the Personal Information of EEA Residents.&nbsp; By providing Personal Information to StoryPlace for the purpose of obtaining Services, you consent to the processing of such data in the United States.&nbsp; The transfer of your Personal Information to the United States is necessary for the performance of a contract between you and StoryPlace for obtaining Services.&nbsp;</p>
                <p>Please note that the United States does not have data protection laws equivalent to those in the EEA and other jurisdictions.</p>
                <p>Notifications and Communications from Our Site</p>
                <h3>Communications Regarding Our Services</h3>
                <p>We will send you email notifications and free newsletters from time to time with offers, suggestions and other information.&nbsp; Some notifications are communications relating to us and our Services.&nbsp; You may &ldquo;opt-out&rdquo; from receiving such communications by following the &ldquo;Unsubscribe&rdquo; instructions provided in the e-mail.&nbsp;</p>
                <h3>Legal or Security Communications</h3>
                <p>We also send out notices that are required for legal or security purposes.&nbsp; For example, certain notifications are sent for your own protection.&nbsp; In other cases, these notifications involve changes to various legal agreements, such as the Privacy Policy or Terms of Use.&nbsp; Generally, you may not opt out of such emails.</p>
                <h3>Account and Order Communications</h3>
                <p>If you subscribe to our Services, we may send you communications regarding such Services.&nbsp; We may also send communications providing customer support or responses to questions regarding the operation of the Services.&nbsp; Generally, you may not opt out of such emails.</p>
                <h3>Deleting Your Information</h3>
                <p>If you want us to delete your Personal Information and your account, please contact us at support@storyplace.com&nbsp; with your request.&nbsp; We will take steps to delete your information as soon as we can, but some information may remain in archived/backup copies for our records or as otherwise required by law.</p>
                <h3>Accessing Your Personal Information</h3>
                <p>Registered users of our Services can access their profile information in their settings and update such information.</p>
                <p>Personal Information Retention</p>
                <p>We retain the Personal Information we receive as described in this Privacy Policy for as long as you use our Services or as necessary to fulfill the purpose(s) for which it was collected, provide our Services, resolve disputes, establish legal defenses, conduct audits, pursue legitimate business purposes, enforce our agreements, and comply with applicable laws.</p>
                <p>Links to Other Sites</p>
                <p>If you follow any links that direct you away from the Site, including links to social media sites or to sites for payment options, among others, this Privacy Policy will not apply to your activity on the other Sites you visit. We do not control the privacy policies or the privacy practices of any third parties.&nbsp;</p>
                <p>Privacy in Submitted Materials and User Content</p>
                <p>If you submit any content to us or share such content with other users you must abide by the <a href="https://storyplacestudio.com/terms/" target="_blank" rel="noopener noreferrer">Terms of Use</a> for conditions relating to such materials.&nbsp; We will never ask you to submit any sensitive Personal Information, such as information related to racial or ethnic origin, political opinions, religion or other beliefs; health, biometric or genetic information; or other potentially sensitive information.&nbsp; We ask you to use caution you in submitting information through the Services.</p>
                <p>Security Policy</p>
                <p>We take commercially reasonable steps to protect our customers&rsquo; Personal Information against unauthorized disclosure or loss.&nbsp; However, no data transmission over the Internet can be guaranteed to be 100% secure.&nbsp; Therefore, while we strive to protect user information we cannot ensure or warrant the security of any information you transmit to us or from the Site.&nbsp; You engage in such transmissions at your risk.</p>
                <p>If you believe your Personal Information is being improperly used by us or any third party, please immediately notify us via email at support@storyplace.com.</p>
                <p>Children Under 13</p>
                <p>This Site is restricted to the use of individuals at least 16 years old and of legal age to form a binding contract in their place of residence.&nbsp; No portion of the Site is directed to children under the age of 13.&nbsp; Consequently, we do not knowingly collect personal identifying information from any person we know is a child under the age of 13.&nbsp; If we learn that we have collected personal information from a child under age 13 we will delete that information as quickly as possible.&nbsp; If you are a parent or guardian of a child under 13 years of age and you believe your child has provided us with Personal Information, please contact us at support@storyplace.com.</p>
                <h3>Your California Privacy Rights</h3>
                <p>The following section pertains to the rights of individuals or households in California (&ldquo;California consumers&rdquo;).&nbsp;</p>
                <ul>
                    <li><em>Civil Code Section 1798.83</em></li>
                </ul>
                <p>Under certain circumstances, California Civil Code Section 1798.83 states that, upon receipt of a request by a California consumer, a business may be required to provide detailed information regarding how that business has shared that customer&rsquo;s Personal Information with third parties for direct marking purposes. However, the foregoing does not apply to businesses like ours that do not disclose Personal Information to third parties for direct marketing purposes without prior approval or give customers a free mechanism to opt out of having their Personal Information disclosed to third parties for their direct marketing purposes.</p>
                <ul>
                    <li><em>Rights under the CCPA</em></li>
                </ul>
                <p>As of January 1, 2020, the CCPA (California Civil Code Section 1798.100 <em>et seq.</em>) will provide California consumers with additional rights regarding Personal Information that identifies, relates to, describes, is capable of being associated with, or could reasonably be linked, directly or indirectly with a particular consumer or household. The categories of Personal Information we collect are generally described above but differ for individual consumers depending on the Services used by such consumers.</p>
                <p>Under the CCPA, qualifying California consumers may have the following rights:</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Right to Know and Right to Delete</strong></span><strong>.</strong></p>
                <p>A California consumer has the right to request that we disclose what Personal Information we collect, use, disclose and sell. A California consumer also has the right to submit requests to delete Personal Information.</p>
                <p>When we receive a request to know or delete from a California consumer, we will confirm receipt of the request within 10 days and provide information about how we will process the request, including our verification process. We will respond to such requests within 45 days.</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Right for Disclosure of Information</strong></span><strong>.</strong></p>
                <p>A California consumer may also submit requests that we disclose specific types or categories of Personal Information that we collect.</p>
                <p>Under certain circumstances, we will not provide such information, including where the disclosure creates a substantial, articulable and unreasonable risk to the security of that Personal Information, customers&rsquo; account with us, or the security of our systems or networks. We also will not disclose California consumers&rsquo; social security numbers, driver&rsquo;s license numbers or other government-issued identification numbers, financial account numbers, any health insurance or medical identification numbers, or account passwords and security questions and answers.</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Submitting Requests</strong></span></p>
                <p>If you are a California consumer and would like to make any requests under the CCPA, please direct them as follows:</p>
                <p>StoryPlace, Inc., attention: StoryPlace HQ, Privacy Compliance</p>
                <p>450 N Palm Dr.</p>
                <p>Beverly Hills, CA 90210</p>
                <p>support@storyplace.com</p>
                <p><span style={{ textDecoration: 'underline' }}><strong>Verifying Requests</strong></span></p>
                <p>If we receive any request we will use a two-step process for online requests where the California consumer must first, clearly submit the request and then second, separately confirm the request. We will use other appropriate measures to verify requests received by mail or telephone.</p>
                <p>In submitting a request, a California consumer must provide sufficient information to identify the consumer, such as name, e-mail address, home or work address, or other such information that is on record with us so that we can match such information to the Personal Information that we maintain. <span style={{ textDecoration: 'underline' }}>Do not provide social security numbers, driver&rsquo;s license numbers, account numbers,credit or debit card numbers, medical information or health information with requests</span>. If requests are unclear or submitted through means other than outlined above, we will provide the California consumer with specific directions on how to submit the request or remedy any deficiencies. If we cannot verify the identity of the requestor, we may deny the request.</p>
                <p><strong>California Do Not Track Disclosures</strong></p>
                <p>Although some browsers currently offer a &ldquo;do not track (&lsquo;DNT&rsquo;) option,&rdquo; no common industry standard for DNT exists. We therefore do not currently commit to responding to browsers&rsquo; DNT signals.</p>
                <p><strong>Your Rights and Obligations&nbsp;</strong></p>
                <p>We ask that you keep the Personal Information that you provide to us current and that you correct any information you have provided us by contacting us at support@storyplace.com<em>.&nbsp; </em>You represent and warrant that all Personal Information you provide us is true and correct and relates to you and not to any other person.&nbsp;</p>
                <p>If you are a resident of the EEA and wish to access or correct the Personal Information that StoryPlace has about you or have any questions relating to the processing of your Personal Information, please contact us at support@storyplace.com with the subject line &ldquo;GDPR Data.&rdquo;&nbsp;</p>
                <p>If you use the Site, you are responsible for maintaining the confidentiality of your account and for restricting access to your computer or device, and you agree to accept responsibility for all activities that occur under your account.&nbsp;</p>
            </LegalContainer>

        </>

    )
}


export default Terms;